theme: jekyll-theme-cayman
<!-------------------Index------------------->

<!DOCTYPE html>
<html lang="en">

    <!-------------------Head------------------->
    <head id="top">

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-161539766-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-161539766-1');
        </script>

        <meta charset="UTF-8">
        <title>Jessica Prague</title>
        <meta name="Description" content="Jessica Prague">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-------------------Linking CSS------------------->
        <link rel="stylesheet" href="styles/all.css" type="text/css">
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />

        <!-------------------Icons------------------->
        <link rel="icon" type="image/x-icon" href="jp-favicon.ico"/>


        <!-------------------Javascript------------------->
        <script src="js/jquery-3.4.1.min.js"></script>
        <script src="js/parallax.min.js"></script>
