<!-------------------About Page------------------->

<!DOCTYPE html>
<html lang="en">

    <!-------------------Head------------------->
    <head id="top">

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-161539766-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-161539766-1');
        </script>

        <meta charset="UTF-8">
        <title>About • Jessica Prague</title>
        <meta name="Description" content="Jessica Prague">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-------------------Linking CSS------------------->
        <link rel="stylesheet" href="styles/all.css" type="text/css">

        <!-------------------Icons------------------->
        <link rel="icon" type="image/x-icon" href="jp-favicon.ico"/>


        <!-------------------Javascript------------------->
        <script src="js/jquery-3.4.1.min.js"></script>
        <script src="js/parallax.min.js"></script>
        <script>
            /* Scroll button appears on scroll */
            $(window).scroll(function(){
                if ($(this).scrollTop() > 20) {
                    $('.scroll-to-top').removeClass('no-display');
                } else {
                    $('.scroll-to-top').addClass('no-display');
                }
            });
            /* Smooth Scrolling */
            $(document).ready(function(){
                $("a").on('click', function(event) {
                    if (this.hash !== "") {
                        event.preventDefault();
                        var hash = this.hash;
                        $('html, body').animate({
                            scrollTop: $(hash).offset().top
                        }, 500, function(){
                            window.location.hash = hash;
                        });
                    }
                });
            });
        </script>
    </head>

    <body>
        <!-------------------Navigation------------------->
        <header class="header">
            <h5 class="jp"><a href="index.html">Jessica Prague</a></h5>
            <ul class="main-nav">
                <li><a href="index.html">Work</a></li>
                <li><a href="about.html" class="active">My Story</a></li>
                <li><a href="Jessica_Prague_Resume.pdf" target="_blank">Resume</a></li>
            </ul>
        </header> 

        <!-------------------Parallax Effect (no text)------------------->
        <div class="parallax" id = "marble-para" data-parallax="scroll" data-z-index="1" data-image-src="images/marble.png">
            <div class="paratext">  
            </div>
        </div>

        <!-------------------Links------------------->
        <div class="places">
            <h6>
                <span class="line cornellline"><a href="http://infosci.cornell.edu/" target="_blank">@Cornell</a></span>  •  
                <span class="line voxline"><a href="https://www.voxmedia.com/a/vm" target="_blank">@VoxMedia</a></span>  •  
                <span class="line facebookline"><a href="https://facebook.design/" target="_blank">@Facebook</a></span>
            </h6>
        </div>

        <!-------------------About Me------------------->
        <div class="about-me-container">
            <div class="about-me-text">
                <h5 class="gray">About Me</h5>
                <h4>Hello!</h4>
                <p>
                    I'm Jessica, a product designer who loves to solve problems and design beautiful, intuitive experiences that make an impact, both big and small. Currently, I am a senior at <a class = "cornellred link" href="http://infosci.cornell.edu/" target="_blank">Cornell University</a> studying information science with concentrations in User Experience and Digital Culture and Production, along with a minor in Business. In summer 2018, I was a product design intern at <a class = "orange link" href="https://www.voxmedia.com/a/vm" target="_blank">Vox Media</a>, and this past summer, I interned at <a class = "blue link" href="https://facebook.design/" target="_blank">Facebook</a>. I will be returning there as a product designer in August 2020.  
                </p>
            </div>
            <div class="about-me-image">
                <img class="shadow" alt="picture of Jessica" src="images/jessicaPrague.png"/>
            </div>
        </div>
        <div class="about-me-container2">
            <p>
                In Fall 2017, I decided to take <a class = "cornellred link" href="https://medium.com/intro-to-digital-product-design" target="_blank">Intro to Digital Product Design</a>, a student-taught course at Cornell, and this class truly changed my life. I immediately fell in love with user experience design, a space that combines my passions for design, business, psychology, multi-faceted problem-solving, and social change.

                At Cornell, I am a product designer for <a class="cornellred link" href="https://www.cornellappdev.com/" target="_blank">Cornell AppDev</a>, Computer Science Instructor for <a class="blue link" href="https://junilearning.com/" target="_blank">Juni Learning</a>, and Teaching Assistant for Design and Programming for the Web <a class="purple link" href="https://classes.cornell.edu/browse/roster/FA19/class/CS/1300" target="_blank">(CS 1300)</a>.
            </p>
            <p class="bottom-para">
                When I'm not knee-deep in sketch files, you can find me fidgeting with Rubik's Cubes, binge-watching Netflix shows, running, and traveling! I am a team player, always challenging myself and open to new and exciting opportunities. Let's chat! Feel free to message me at <a class="blue link" href="mailto:jnp49@cornell.edu">jnp49@cornell.edu</a>.
            </p>
        </div>

        <!-------------------Footer------------------->
        <div class="footer">
            <h4 class="line blueline"><a href="mailto:jnp49@cornell.edu"> 👋 Let's Get In Touch!</a></h4>
            <div class="social">                
                <a href="https://www.linkedin.com/in/jessicaprague/" target="_blank"> <img class="icon" src="images/linkedin.png" alt="linkedin"/> </a>
                <a href="https://medium.com/@jessicaprague/" target="_blank"> <img class="icon" src="images/medium.png" alt="medium"/> </a>
                <a href="https://twitter.com/jessicaprague" target="_blank"> <img class="icon" src="images/twitter.png" alt="twitter"/> </a>
                <a href="https://www.instagram.com/jesseprague/" target="_blank"> <img class="icon" src="images/instagramlogo.png" alt="instagram"/> </a>
            </div>
            <h6 class="name"><span id="blueStar">★</span> DESIGNED AND CODED WITH <span class="love">LOVE</span> BY JESSICA PRAGUE <span id="blueStar">★</span></h6>
        </div>
        <!-------------------Scroll To Top------------------->
        <a href="#top" aria-label="scroll to top" class="scroll-to-top"></a>
    </body>
</html>
